name: flutter_assignment_shubhangi
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.12.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.4.1
  cloud_firestore: ^4.3.1
  get: ^4.3.8
  provider: ^6.0.4
  intl: ^0.17.0
  shared_preferences: ^2.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/


